name: Rest-assured tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh ./get-docker.sh --dry-run
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Checkout code
        uses: actions/checkout@v4